pipelines:
  - test_pipeline:
    - graph_generate: cube_test
      n: 25
      weighted: 1
    - coarsening: matching
      type: random
      count: 5
    - coarsening: matching
      type: hard
      until: trigger
      trigger: vertexes
      upper_bound: 10

wrappers:
  - call_test:
    - do: test_pipeline
    - graph_export_edges: ../graph_data/out.txt

run:
  - call_test